# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{voomify_utility_drawer}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Russell Edens"]
  s.date = %q{2010-10-07}
  s.description = %q{This gem contains a bunch of useful utilities.}
  s.email = %q{russell@voomify.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/base/httparty.rb",
     "lib/extensions/hash.rb",
     "lib/extensions/kernel.rb",
     "lib/replace_rake_tasks.rb",
     "lib/utility_drawer.rb",
     "lib/voomify/config.rb"
  ]
  s.homepage = %q{http://www.github.com/voomify/utility_drawer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Voomify useful classes that most of our projects use}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

